// mfe-sources/shared/angular-shared/src/lifecycle/create-mfe-bootstrap.ts
import { Type, NgModuleRef } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import type { MFELifecycle } from '@mfe/types';

/**
 * Creates mount and unmount functions for an Angular MFE
 *
 * @param mfeName - Display name for logging
 * @param moduleType - Angular module class to bootstrap
 * @param componentSelector - HTML selector for the root component (default: 'app-root')
 * @returns MFELifecycle object with mount and unmount methods
 *
 * @example
 * ```typescript
 * import { createAngularMFEBootstrap } from '@mfe/angular-shared';
 * import { AppModule } from './app.module';
 *
 * window.DashboardLandingPageMFE = createAngularMFEBootstrap(
 *   'Dashboard Landing Page MFE',
 *   AppModule
 * );
 * ```
 */
export function createAngularMFEBootstrap<T>(
  mfeName: string,
  moduleType: Type<T>,
  componentSelector: string = 'app-root'
): MFELifecycle {
  let moduleRef: NgModuleRef<T> | null = null;

  return {
    mount(elementId: string) {
      const element = document.getElementById(elementId);
      if (element) {
        // Clear any existing content
        element.innerHTML = '';
        const appRoot = document.createElement(componentSelector);
        element.appendChild(appRoot);

        platformBrowserDynamic()
          .bootstrapModule(moduleType)
          .then(ref => {
            moduleRef = ref;
            console.log(`${mfeName} mounted to`, elementId);
          })
          .catch(err => console.error(err));
      }
    },

    unmount(elementId: string) {
      if (moduleRef) {
        moduleRef.destroy();
        moduleRef = null;
      }
      const element = document.getElementById(elementId);
      if (element) {
        element.innerHTML = '';
      }
      console.log(`${mfeName} unmounted from`, elementId);
    }
  };
}

// mfe-sources/shared/react-shared/src/lifecycle/createMFEBootstrap.tsx
import React, { ComponentType } from 'react';
import ReactDOM from 'react-dom/client';
import type { MFELifecycle } from '@mfe/types';

/**
 * Creates mount and unmount functions for a React MFE
 *
 * @param mfeName - Display name for logging
 * @param Component - React component to mount
 * @returns MFELifecycle object with mount and unmount methods
 *
 * @example
 * ```tsx
 * import { createMFEBootstrap } from '@mfe/react-shared';
 * import Header from './Header';
 *
 * window.HeaderMFE = createMFEBootstrap('Header MFE', Header);
 * ```
 */
export function createMFEBootstrap<P = {}>(
  mfeName: string,
  Component: ComponentType<P>
): MFELifecycle {
  let root: ReactDOM.Root | null = null;

  return {
    mount(elementId: string) {
      const element = document.getElementById(elementId);
      if (element) {
        // Clear any existing content
        element.innerHTML = '';
        root = ReactDOM.createRoot(element);
        root.render(<Component />);
        console.log(`${mfeName} mounted to`, elementId);
      }
    },

    unmount(elementId: string) {
      if (root) {
        root.unmount();
        root = null;
      }
      const element = document.getElementById(elementId);
      if (element) {
        element.innerHTML = '';
      }
      console.log(`${mfeName} unmounted from`, elementId);
    }
  };
}
